from datetime import datetime
from pathlib import Path

from config import REPORT_DIR, SEVERITY_ORDER


SEVERITY_EMOJI = {
    "critical": "!!!",
    "high": "!!",
    "medium": "!",
    "low": "~",
    "info": "i",
}

SEVERITY_COLOR = {
    "critical": "red",
    "high": "red",
    "medium": "yellow",
    "low": "cyan",
    "info": "gray",
}


def generate_report(result, project_path: str, project_stats: dict, analyzers_used: list[str]) -> Path:
    REPORT_DIR.mkdir(exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    project_name = Path(project_path).name
    report_file = REPORT_DIR / f"bug_report_{project_name}_{timestamp}.md"

    sorted_bugs = result.sorted_bugs()

    lines = []
    lines.append(f"# BugHunter Report: {project_name}")
    lines.append(f"")
    lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"**Project:** `{project_path}`")
    lines.append(f"**Analyzers:** {', '.join(analyzers_used)}")
    lines.append(f"")

    lines.append(f"## Summary")
    lines.append(f"")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Files analyzed | {result.files_analyzed} |")
    lines.append(f"| Total lines | {project_stats.get('total_lines', 'N/A'):,} |")
    lines.append(f"| Bugs found | {len(result.bugs)} |")

    severity_counts = {}
    for bug in sorted_bugs:
        severity_counts[bug.severity] = severity_counts.get(bug.severity, 0) + 1

    for sev in ["critical", "high", "medium", "low", "info"]:
        count = severity_counts.get(sev, 0)
        if count > 0:
            lines.append(f"| {SEVERITY_EMOJI[sev]} {sev.capitalize()} | {count} |")

    if result.errors:
        lines.append(f"| Errors | {len(result.errors)} |")

    lines.append(f"")

    if project_stats.get("languages"):
        lines.append(f"### Languages Detected")
        lines.append(f"")
        for lang, count in sorted(project_stats["languages"].items(), key=lambda x: -x[1]):
            lines.append(f"- **{lang}**: {count} files")
        lines.append(f"")

    if result.errors:
        lines.append(f"## Errors During Analysis")
        lines.append(f"")
        for err in result.errors:
            lines.append(f"- {err}")
        lines.append(f"")

    category_groups = {}
    for bug in sorted_bugs:
        cat = bug.category
        if cat not in category_groups:
            category_groups[cat] = []
        category_groups[cat].append(bug)

    category_order = ["security", "logic", "error-handling", "concurrency",
                       "resource-management", "performance", "syntax", "code-quality"]

    for cat in category_order:
        if cat not in category_groups:
            continue
        bugs = category_groups[cat]
        lines.append(f"## {cat.replace('-', ' ').title()} ({len(bugs)})")
        lines.append(f"")
        for bug in bugs:
            lines.append(f"### [{SEVERITY_EMOJI[bug.severity].upper()}] {bug.title}")
            lines.append(f"")
            lines.append(f"- **File:** `{bug.file}:{bug.line}`")
            lines.append(f"- **Severity:** {bug.severity.upper()}")
            lines.append(f"- **Confidence:** {bug.confidence:.0%}")
            lines.append(f"- **Analyzer:** {bug.analyzer}")
            lines.append(f"")
            lines.append(f"**Problem:** {bug.description}")
            lines.append(f"")
            lines.append(f"**Fix:** {bug.suggestion}")
            lines.append(f"")
            if bug.code_snippet:
                lines.append(f"<details>")
                lines.append(f"<summary>Code</summary>")
                lines.append(f"")
                lines.append(f"```")
                lines.append(bug.code_snippet)
                lines.append(f"```")
                lines.append(f"</details>")
                lines.append(f"")
            lines.append(f"---")
            lines.append(f"")

    for cat, bugs in category_groups.items():
        if cat not in category_order:
            lines.append(f"## {cat.replace('-', ' ').title()} ({len(bugs)})")
            lines.append(f"")
            for bug in bugs:
                lines.append(f"### [{SEVERITY_EMOJI[bug.severity].upper()}] {bug.title}")
                lines.append(f"- **File:** `{bug.file}:{bug.line}`")
                lines.append(f"- **Severity:** {bug.severity.upper()}")
                lines.append(f"**Problem:** {bug.description}")
                lines.append(f"**Fix:** {bug.suggestion}")
                lines.append(f"---")
            lines.append(f"")

    if not sorted_bugs:
        lines.append(f"## No Bugs Found")
        lines.append(f"")
        lines.append(f"The analysis completed without finding any issues.")
        lines.append(f"")

    lines.append(f"")
    lines.append(f"---")
    lines.append(f"*Generated by BugHunter*")

    report_file.write_text("\n".join(lines), encoding="utf-8")
    return report_file
